/**
 * Spotify artist pages, keyed by cover filename.
 *
 * Generated by scripts/resolve-artists.mjs — run `npm run artists` after
 * adding a cover. Names missing here fall back to a Spotify search.
 */
export const ARTIST_LINKS: Record<string, string> = {
  "Chilli Beans.": 'https://open.spotify.com/artist/48apiuEaHdddhdRvfFjPB7',
  "Hitsujibungaku": 'https://open.spotify.com/artist/6S8w5rLsEwjN21jQeRES0n',
  "NMIXX": 'https://open.spotify.com/artist/28ot3wh4oNmoFOdVajibBl',
  "Regallily": 'https://open.spotify.com/artist/75eQ7NabzgaaUYcrqSY0FK',
  "SHISHAMO": 'https://open.spotify.com/artist/6MGHit7sV38BhpChZYByFv',
  "Saucy Dog": 'https://open.spotify.com/artist/4WqXqPmUuenMIr4QaFrZXN',
  "Serani Poji": 'https://open.spotify.com/artist/6JzJhoOtjzVLZpMi3Ppz3T',
  "ZOOKARADERU": 'https://open.spotify.com/artist/0mkwliKa9Bf7kdXMV1iuMp',
  "indigo la End": 'https://open.spotify.com/artist/26ZBeXl5Gqr3TAv2itmyCU',
}
