#!/usr/bin/env node
/**
 * Turns the filenames in src/assets/images into Spotify artist links.
 *
 * The covers are named after the artist, which is enough to look each one
 * up through the Search API. Run this once after adding or renaming a
 * cover; the result is committed, so the site never has to hit Spotify
 * for something that does not change.
 *
 *   npm run artists
 *
 * Anything it cannot resolve is left out, and the app falls back to a
 * Spotify search URL for that name — a worse link, but never a dead one.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const IMAGES = 'src/assets/images'
const OUT = 'src/features/showcase/artist-links.ts'

function readEnv(path) {
  try {
    return Object.fromEntries(
      readFileSync(path, 'utf8')
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#'))
        .map((l) => {
          const at = l.indexOf('=')
          return [l.slice(0, at).trim(), l.slice(at + 1).trim().replace(/^["']|["']$/g, '')]
        }),
    )
  } catch {
    return {}
  }
}

const env = { ...readEnv('.env.local'), ...process.env }
const { SPOTIFY_CLIENT_ID: id, SPOTIFY_CLIENT_SECRET: secret } = env
if (!id || !secret) {
  console.error('\n  Need SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET in .env.local\n')
  process.exit(1)
}

// Client credentials: this looks up public catalogue data, so it needs no
// user token and none of the refresh-token machinery the site uses.
const tokenRes = await fetch('https://accounts.spotify.com/api/token', {
  method: 'POST',
  headers: {
    Authorization: `Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`,
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  body: new URLSearchParams({ grant_type: 'client_credentials' }),
})
if (!tokenRes.ok) {
  console.error(`  token request failed: ${tokenRes.status} ${await tokenRes.text()}`)
  process.exit(1)
}
const { access_token: token } = await tokenRes.json()

const names = readdirSync(IMAGES)
  .filter((f) => /\.(png|jpe?g|webp)$/i.test(f))
  .map((f) => f.replace(/\.[^.]+$/, ''))
  .sort()

const links = {}
for (const name of names) {
  const url = `https://api.spotify.com/v1/search?type=artist&limit=3&q=${encodeURIComponent(name)}`
  const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } })
  if (!res.ok) {
    console.log(`  ${name.padEnd(22)} search failed (${res.status})`)
    continue
  }
  const items = (await res.json()).artists?.items ?? []
  // Prefer an exact name match; Spotify's first result is not always it.
  const hit =
    items.find((a) => a.name.toLowerCase() === name.toLowerCase()) ?? items[0]
  if (!hit) {
    console.log(`  ${name.padEnd(22)} no match`)
    continue
  }
  links[name] = hit.external_urls.spotify
  const exact = hit.name.toLowerCase() === name.toLowerCase() ? '' : `  (matched "${hit.name}")`
  console.log(`  ${name.padEnd(22)} ${hit.external_urls.spotify}${exact}`)
}

const body = Object.entries(links)
  .map(([k, v]) => `  ${JSON.stringify(k)}: '${v}',`)
  .join('\n')

writeFileSync(
  OUT,
  `/**
 * Spotify artist pages, keyed by cover filename.
 *
 * Generated by scripts/resolve-artists.mjs — run \`npm run artists\` after
 * adding a cover. Names missing here fall back to a Spotify search.
 */
export const ARTIST_LINKS: Record<string, string> = {
${body}
}
`,
)
console.log(`\n  wrote ${OUT} (${Object.keys(links).length}/${names.length} resolved)`)
